name: "infra"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ELECTRON_SKIP_BINARY_DOWNLOAD: 1

jobs:
  test:
    name: "test no error"
    runs-on: ubuntu-20.04
    steps:
    - uses: ikalnytskyi/action-setup-postgres@v5
      with:
        username: user
        password: password
        database: postgres
        port: 5432
      id: postgres

    - run: node test.mjs
